### ISSUE TITLE
API - Create Resources - Offer Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#10]
## Background
Create the API endpoints for the `Offer` Resource.

https://www.stellar.org/developers/horizon/reference/resources/offer.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **Account Offers** _Collection_ `/accounts/:account_id/offers`

**Comment by bryanjos** [comment]
This is done. Closing
