### ISSUE TITLE
API - Create Resources - Operation Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#11]
## Background
Create the API endpoints for the `Operation` Resource.

https://www.stellar.org/developers/horizon/reference/resources/operation.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **All Operations** _Collection_ `/operations`
- [x] **Operations Details** _Single_ `/operations/:id`
- [ ] **Ledger Operations** _Collection_ `/ledgers/{id}/operations{?cursor,limit,order}`
- [x] **Account Operations** _Collection_ `/accounts/:account_id/operations`
- [ ] **Account Payments** _Collection_ `/accounts/:account_id/payments`

**Comment by bryanjos** [comment]
This is a duplicate. So closing
