### ISSUE TITLE
API - Create Resources - Page Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#13]
## Background
Create the API endpoints for the `Page` Resource.

https://www.stellar.org/developers/horizon/reference/resources/page.html

## Endpoints
Any endpoint that provides a collection of resources will represent them as pages.
- [ ] Checklist item(s)?

**Comment by iamjoshfrank** [comment]
@bryanjos - seems like maybe there isn't anything to implement here?

**Comment by bryanjos** [comment]
Correct. Closing
