### ISSUE TITLE
API - Create Resources - Payment Path Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#14]
## Background
Create the API endpoints for the `Payment Path` Resource.

https://www.stellar.org/developers/horizon/reference/resources/path.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **Find Payment Paths** _Collection_ `/paths`

**Comment by bryanjos** [comment]
All have been added. Closing
