### ISSUE TITLE
API - Create Resources - Trade Aggregation Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#16]
## Background
Create the API endpoints for the `Trade Aggregation` Resource.

https://www.stellar.org/developers/horizon/reference/resources/trade_aggregation.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **Trade Aggregations** _Collection_	`/trade_aggregations?{orderbook_params}`

**Comment by bryanjos** [comment]
All have been added. Closing
