### ISSUE TITLE
API - Create Resources - Account Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#5]
## Background
Create the API endpoints for the `Account` Resource.
https://www.stellar.org/developers/horizon/reference/resources/account.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **Account Details** _Single_ `/accounts/:id`
- [x] **Account Data** _Single_ `/accounts/:id/data/:key`
- [x] **Account Transactions** _Collection_ `/accounts/:account_id/transactions`
- [x] **Account Operations** _Collection_ `/accounts/:account_id/operations`
- [x] **Account Payments** _Collection_ `/accounts/:account_id/payments`
- [x] **Account Effects** _Collection_ `/accounts/:account_id/effects`
- [x] **Account Offers** _Collection_ `/accounts/:account_id/offers`

**Comment by iamjoshfrank** [comment]
Assigning to @bryanjos to confirm this is already complete.

**Comment by bryanjos** [comment]
They are done. Closing
