### ISSUE TITLE
API - Create Resources - Asset Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#6]
## Background
Create the API endpoints for the `Asset` Resource.

https://www.stellar.org/developers/horizon/reference/resources/asset.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **All Assets** _Collection_ `/assets (GET)`

**Comment by iamjoshfrank** [comment]
Assigning to @bryanjos to this is already complete.

**Comment by bryanjos** [comment]
Also done. Closing
