### ISSUE TITLE
API - Create Resources - Data Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#7]
## Background
Create the API endpoints for the `Data` Resource.

https://www.stellar.org/developers/horizon/reference/resources/data.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
! No endpoint listed on https://www.stellar.org/developers/horizon/reference/resources/data.html

**Comment by iamjoshfrank** [comment]
@bryanjos - don't see an endpoint listed on the reference page for the `Data` resource, so not sure what to put in the checklist. Via Slack, you said this is complete, so I'll leave it to you to create a checklist and/or close.

**Comment by bryanjos** [comment]
There was only one and it was part of account. Already taken care of so closing this
