### ISSUE TITLE
API - Create Resources - Effect Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#8]
## Background
Create the API endpoints for the `Effect` Resource.

https://www.stellar.org/developers/horizon/reference/resources/effect.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **All Effects** _Collection_ `/effects`
- [x] **Single Effect** _Single_ `/effects/:id`
- [x] **Operation Effects** _Collection_ `/operations/:id/effects`
- [x] **Account Effects** _Collection_ `/accounts/:account_id/effects`
- [x] **Ledger Effects** _Collection_ `/ledgers/:ledger_id/effects`

**Comment by bryanjos** [comment]
All have been added. Closing
