### ISSUE TITLE
API - Create Resources - Ledger Endpoints

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/elixir-stellar-client#9]
## Background
Create the API endpoints for the `Ledger` Resource.

https://www.stellar.org/developers/horizon/reference/resources/ledger.html

## Endpoints
**Resource** _Type_ `Resource URI Template`
- [x] **All ledgers** _Collection_ `/ledgers`
- [x] **Single Ledger** _Single_ `/ledgers/:id`
- [x] **Ledger Transactions** _Collection_ `/ledgers/:ledger_id/transactions`
- [x] **Ledger Operations** _Collection_ `/ledgers/:ledger_id/operations`
- [x] **Ledger Payments** _Collection_ `/ledgers/:ledger_id/payments`
- [x] **Ledger Effects** _Collection_ `/ledgers/:ledger_id/effects`

**Comment by bryanjos** [comment]
All have been added. Closing
